{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "web-search-mcp.fullname" . }}
  labels:
    {{- include "web-search-mcp.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.secrets | nindent 2 }}
{{- end }}
